"""enable encryption at rest

Revision ID: 195d959d6699
Revises: 7aa6abba6e12
Create Date: 2025-04-09 16:35:01.859723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from engine.db.encryption_utils import EncryptedJSON

# revision identifiers, used by Alembic.
revision: str = '195d959d6699'
down_revision: Union[str, None] = '7aa6abba6e12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_relations')
    # ### end Alembic commands ###


def downgrade() -> None:

    
    op.create_table('module_relations',
    sa.Column('source_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('target_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('relation_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['source_id'], ['modules.module_id'], name='module_relations_source_id_fkey'),
    sa.ForeignKeyConstraint(['target_id'], ['modules.module_id'], name='module_relations_target_id_fkey'),
    sa.PrimaryKeyConstraint('source_id', 'target_id', 'relation_type', name='module_relations_pkey')
    )
    # ### end Alembic commands ###
