"""add cascade delete for module

Revision ID: 1b860f044ac1
Revises: 159009b62982
Create Date: 2025-01-29 20:34:42.928467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b860f044ac1'
down_revision: Union[str, None] = '159009b62982'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('agent_status_module_id_fkey', 'agent_status', type_='foreignkey')
    op.create_foreign_key(None, 'agent_status', 'modules', ['module_id'], ['module_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_status', type_='foreignkey')
    op.create_foreign_key('agent_status_module_id_fkey', 'agent_status', 'modules', ['module_id'], ['module_id'])
    # ### end Alembic commands ###
