"""add module api keys table

Revision ID: 2f48148cb302
Revises: 08b81d37771a
Create Date: 2025-03-26 23:57:33.760067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f48148cb302'
down_revision: Union[str, None] = '08b81d37771a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('module_api_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_module_api_keys_api_key'), 'module_api_keys', ['api_key'], unique=True)
    op.drop_table('work_manifests')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_manifests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('module_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], name='work_manifests_module_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='work_manifests_pkey')
    )
    op.drop_index(op.f('ix_module_api_keys_api_key'), table_name='module_api_keys')
    op.drop_table('module_api_keys')
    # ### end Alembic commands ###
