"""add module provide

Revision ID: 3084ae1366e8
Revises: c5684a8455b8
Create Date: 2025-04-11 21:09:48.662724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3084ae1366e8'
down_revision: Union[str, None] = 'c5684a8455b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TYPE IF EXISTS providetype CASCADE')


    op.create_table('module_provides',
    sa.Column('provider_id', sa.String(), nullable=False),
    sa.Column('receiver_id', sa.String(), nullable=False),
    sa.Column('resource_type', sa.Enum('WORKSPACE', 'TOOL', name='providetype'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receiver_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('provider_id', 'receiver_id', 'resource_type')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('module_provides')

    op.execute('DROP TYPE IF EXISTS providetype CASCADE')

    # ### end Alembic commands ###
