"""remove workfloe data table

Revision ID: 33a76753d419
Revises: b308bde3bf12
Create Date: 2025-02-16 13:23:55.213813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33a76753d419'
down_revision: Union[str, None] = 'b308bde3bf12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'workflow_stores', 'modules', ['module_id'], ['module_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workflow_stores', type_='foreignkey')
    # ### end Alembic commands ###
