"""add session_id to workflows

Revision ID: 4f8cb01d9da8
Revises: 6948d3231316
Create Date: 2025-02-07 14:16:19.870929

"""
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa
import uuid


# revision identifiers, used by Alembic.
revision: str = '4f8cb01d9da8'
down_revision: Union[str, None] = '6948d3231316'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Add column as nullable first
    op.add_column('chat_history', sa.Column('session_id', sa.String(), nullable=True))
    
    # Update existing rows with default value
    op.execute("UPDATE chat_history SET session_id = '00000000-0000-0000-0000-000000000000'")
    
    # Make column not nullable
    op.alter_column('chat_history', 'session_id',
                     existing_type=sa.String(),
                     nullable=False)
    
    # Update constraints
    op.drop_constraint('chat_history_module_id_section_timestamp_key', 'chat_history', type_='unique')
    op.create_unique_constraint(None, 'chat_history', ['module_id', 'section', 'timestamp', 'session_id'])


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_history', type_='unique')
    op.create_unique_constraint('chat_history_module_id_section_timestamp_key', 'chat_history', ['module_id', 'section', 'timestamp'])
    op.drop_column('chat_history', 'session_id')
    # ### end Alembic commands ###
