"""create initial tables

Revision ID: 53bcfdb9ee4d
Revises: 2cf6212c3cf7
Create Date: 2025-01-25 06:30:59.371071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53bcfdb9ee4d'
down_revision: Union[str, None] = '2cf6212c3cf7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
