"""add workflow stores

Revision ID: 550f35f4094d
Revises: 82c5c646edb2
Create Date: 2025-02-16 12:42:36.971088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '550f35f4094d'
down_revision: Union[str, None] = '82c5c646edb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_stores',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('workflow', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_workflow_store_lookup', 'workflow_stores', ['module_id', 'workflow', 'collection'], unique=False)
    op.create_table('workflow_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('workflow_type', sa.String(), nullable=False),
    sa.Column('collection', sa.String(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'workflow_type', 'collection', name='unique_workflow_data')
    )
    op.create_index('idx_workflow_lookup', 'workflow_data', ['module_id', 'workflow_type', 'collection'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_workflow_lookup', table_name='workflow_data')
    op.drop_table('workflow_data')
    op.drop_index('idx_workflow_store_lookup', table_name='workflow_stores')
    op.drop_table('workflow_stores')
    # ### end Alembic commands ###
