"""change tool_callstype

Revision ID: 6fc6692b69f7
Revises: dde76d5a3ca7
Create Date: 2025-02-13 17:50:57.922259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc6692b69f7'
down_revision: Union[str, None] = 'dde76d5a3ca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
