"""add module_name field

Revision ID: 7e0a1909e829
Revises: 8e1b1c958c84
Create Date: 2025-01-25 16:18:30.065477

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e0a1909e829'
down_revision: Union[str, None] = '8e1b1c958c84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('modules', sa.Column('module_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('modules', 'module_name')
    # ### end Alembic commands ###
