"""make content optional

Revision ID: 82c5c646edb2
Revises: c10ed21756d1
Create Date: 2025-02-13 18:15:42.440317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82c5c646edb2'
down_revision: Union[str, None] = 'c10ed21756d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_history', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
