"""create initial tables

Revision ID: 8e1b1c958c84
Revises: a2b0c771ef91
Create Date: 2025-01-25 06:37:37.607844

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e1b1c958c84'
down_revision: Union[str, None] = 'a2b0c771ef91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('message_type', sa.String(), nullable=False),
    sa.Column('tool_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('module_id', 'section', 'timestamp')
    )
    op.create_index('idx_module_section', 'chat_history', ['module_id', 'section'], unique=False)
    op.create_table('modules',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('kit_id', sa.String(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('env_vars', sa.JSON(), nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('projects',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('agent_status',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('stage', sa.Enum('INITIALIZE', 'MAINTAIN', 'REMOVE', name='agent_stage'), nullable=False),
    sa.Column('state', sa.Enum('STANDBY', 'EXECUTING', name='agent_state'), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('module_id')
    )
    op.create_table('module_relations',
    sa.Column('source_id', sa.String(), nullable=False),
    sa.Column('target_id', sa.String(), nullable=False),
    sa.Column('relation_type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['modules.module_id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id')
    )
    op.create_table('project_module_mappings',
    sa.Column('project_id', sa.String(), nullable=False),
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('project_id', 'module_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_module_mappings')
    op.drop_table('module_relations')
    op.drop_table('agent_status')
    op.drop_table('projects')
    op.drop_table('modules')
    op.drop_index('idx_module_section', table_name='chat_history')
    op.drop_table('chat_history')
    # ### end Alembic commands ###
