"""rename section to workflow

Revision ID: a81e6a283380
Revises: 33a76753d419
Create Date: 2025-02-16 14:46:52.185802

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a81e6a283380'
down_revision: Union[str, None] = '33a76753d419'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('workflow', sa.String(), nullable=False))
    op.drop_constraint('chat_history_module_id_section_timestamp_session_id_key', 'chat_history', type_='unique')
    op.drop_index('idx_module_section', table_name='chat_history')
    op.create_index('idx_module_workflow', 'chat_history', ['module_id', 'workflow'], unique=False)
    op.create_unique_constraint(None, 'chat_history', ['module_id', 'workflow', 'timestamp', 'session_id'])
    op.drop_column('chat_history', 'section')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('section', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'chat_history', type_='unique')
    op.drop_index('idx_module_workflow', table_name='chat_history')
    op.create_index('idx_module_section', 'chat_history', ['module_id', 'section'], unique=False)
    op.create_unique_constraint('chat_history_module_id_section_timestamp_session_id_key', 'chat_history', ['module_id', 'section', 'timestamp', 'session_id'])
    op.drop_column('chat_history', 'workflow')
    # ### end Alembic commands ###
