"""add tool_call_id and name to chat history

Revision ID: b3c6f4e02985
Revises: 4f8cb01d9da8
Create Date: 2025-02-13 17:30:16.828564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3c6f4e02985'
down_revision: Union[str, None] = '4f8cb01d9da8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('tool_call_id', sa.String(), nullable=True))
    op.add_column('chat_history', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'name')
    op.drop_column('chat_history', 'tool_call_id')
    # ### end Alembic commands ###
