"""add store config

Revision ID: c356ad4e9aff
Revises: a81e6a283380
Create Date: 2025-02-19 11:51:23.605414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c356ad4e9aff'
down_revision: Union[str, None] = 'a81e6a283380'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vector_store_configs',
    sa.Column('module_id', sa.String(), nullable=False),
    sa.Column('store_name', sa.String(), nullable=False),
    sa.Column('store_type', sa.Enum('CHROMA', 'PINECONE', 'QDRANT', 'WEAVIATE', 'PGVECTOR', 'ELASTICSEARCH', 'OPENSEARCH', name='storetype'), nullable=False),
    sa.Column('embedding_dim', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['module_id'], ['modules.module_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('module_id', 'store_name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vector_store_configs')
    # ### end Alembic commands ###
