"""add workflow stores

Revision ID: efaa991ab7bd
Revises: 550f35f4094d
Create Date: 2025-02-16 13:12:35.189813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efaa991ab7bd'
down_revision: Union[str, None] = '550f35f4094d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
